allowBuilds:
  esbuild: true
  spawn-sync: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.ebad0889e4616a87135b47028b543dd19d940405
  vite-plus: 0.0.0-commit.ebad0889e4616a87135b47028b543dd19d940405
  vitest: 4.1.9
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  web-ext@^10.1.0>addons-linter: '-'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
